# Generated by Django 4.2.1 on 2023-05-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=100)),
                ('lender_email', models.EmailField(max_length=100)),
                ('lender_phone', models.CharField(max_length=100)),
                ('lender_address', models.CharField(max_length=100)),
                ('lender_city', models.CharField(max_length=100)),
                ('lender_state', models.CharField(max_length=100)),
                ('lender_zip', models.CharField(max_length=100)),
                ('lender_country', models.CharField(max_length=100)),
                ('lender_website', models.CharField(max_length=100)),
                ('lender_logo', models.ImageField(blank=True, upload_to='lender_logo')),
                ('lender_description', models.TextField()),
                ('lender_created', models.DateTimeField(auto_now_add=True)),
                ('lender_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lenders',
                'ordering': ['lender_name'],
            },
        ),
    ]
