# Generated by Django 4.2.1 on 2023-05-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0003_lender_is_submitted_to_lender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lender',
            name='is_submitted_to_lender',
        ),
    ]
