# Generated by Django 4.2.1 on 2023-05-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'Deals'},
        ),
    ]
