# Generated by Django 4.2.1 on 2023-05-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_deal_apr_deal_make_deal_model_deal_msrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='deal',
            name='condition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='deal',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
    ]
