# Generated by Django 4.2.1 on 2023-05-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_deal_color_deal_condition_deal_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_submitted_to_lender',
            field=models.BooleanField(default=False),
        ),
    ]
