# Generated by Django 4.2.1 on 2023-05-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_deal_is_submitted_to_lender'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_approved_by_lender',
            field=models.BooleanField(default=False),
        ),
    ]
