# Generated by Django 4.2.1 on 2023-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_deal_is_approved_by_lender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ['title'],
            },
        ),
    ]
