# Generated by Django 4.2.1 on 2023-05-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0007_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
